export const PRESET_TILESETS = [
  { name: 'Outside4 Winter', file: 'Outside4 Winter.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4544, imagewidth: 2176, imageheight: 2414, margin: 1, spacing: 2 },
  { name: 'Outside1 Spring', file: 'Outside1 Spring.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4544, imagewidth: 2176, imageheight: 2414, margin: 1, spacing: 2 },
  { name: 'Outside1 Spring_extruded', file: 'Outside1 Spring_extruded.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4544, imagewidth: 2176, imageheight: 2414, margin: 1, spacing: 2 },
  { name: 'Outside2 Summer', file: 'Outside2 Summer.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4544, imagewidth: 2176, imageheight: 2414, margin: 1, spacing: 2 },
  { name: 'Outside3 Autumn', file: 'Outside3 Autumn.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4544, imagewidth: 2176, imageheight: 2414, margin: 1, spacing: 2 },
  { name: 'Outside', file: 'Outside.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 4016, imagewidth: 2176, imageheight: 2142, margin: 1, spacing: 2 },
  { name: 'spz3zUx_scaled', file: 'spz3zUx_scaled.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 1728, imagewidth: 2176, imageheight: 918, margin: 1, spacing: 2 },
  { name: 'Caves', file: 'Caves.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 1704, imagewidth: 2176, imageheight: 918, margin: 1, spacing: 2 },
  { name: 'Dungeon cave', file: 'Dungeon cave.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 64, imagewidth: 256, imageheight: 256 },
  { name: 'Dungeon forest', file: 'Dungeon forest.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 56, imagewidth: 256, imageheight: 224 },
  { name: 'Factory interior', file: 'Factory interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 224, imagewidth: 256, imageheight: 896 },
  { name: 'Game Corner interior', file: 'Game Corner interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 240, imagewidth: 256, imageheight: 960 },
  { name: 'Graveyard tower interior', file: 'Graveyard tower interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 152, imagewidth: 256, imageheight: 608 },
  { name: 'Gyms interior', file: 'Gyms interior.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 1264, imagewidth: 2176, imageheight: 680, margin: 1, spacing: 2 },
  { name: 'Harbour interior', file: 'Harbour interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 320, imagewidth: 256, imageheight: 1280 },
  { name: 'Department store interior', file: 'Department store interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 392, imagewidth: 256, imageheight: 1568 },
  { name: 'Interior general', file: 'Interior general.png', tilewidth: 32, tileheight: 32, columns: 64, tilecount: 2120, imagewidth: 2176, imageheight: 1156, margin: 1, spacing: 2 },
  { name: 'Mansion interior', file: 'Mansion interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 232, imagewidth: 256, imageheight: 928 },
  { name: 'Mart interior', file: 'Mart interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 144, imagewidth: 256, imageheight: 576 },
  { name: 'Multiplayer rooms', file: 'Multiplayer rooms.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 344, imagewidth: 256, imageheight: 1376 },
  { name: 'Museum interior', file: 'Museum interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 184, imagewidth: 256, imageheight: 736 },
  { name: 'Poke Centre interior', file: 'Poke Centre interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 320, imagewidth: 256, imageheight: 1280 },
  { name: 'Ruins interior', file: 'Ruins interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 128, imagewidth: 256, imageheight: 512 },
  { name: 'Trainer Tower interior', file: 'Trainer Tower interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 440, imagewidth: 256, imageheight: 1760 },
  { name: 'Underground path', file: 'Underground path.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 72, imagewidth: 256, imageheight: 288 },
  { name: 'Underwater', file: 'Underwater.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 112, imagewidth: 256, imageheight: 448 },
  { name: 'Bike shop interior', file: 'Bike shop interior.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 80, imagewidth: 256, imageheight: 320 },
  { name: 'Boat', file: 'Boat.png', tilewidth: 32, tileheight: 32, columns: 8, tilecount: 480, imagewidth: 256, imageheight: 1920 }
];
